# Generated by Django 5.2.12 on 2026-04-19 16:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderedPlaced',
            new_name='OrderPlaced',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='lacality',
            new_name='locality',
        ),
    ]
